"li x15, 1\n\t"
"li t3, 16\n\t"
"li t4, 0\n\t"
"li t6, 8\n\t"
"outer:\n\t"
"li t5, 0\n\t"
"beq %[flag], x15, break\n\t"
"add %[p_tmp1], %[p_x], t4\n\t"
"lh t1, 0(%[p_tmp1])\n\t"
"li x14, 8\n\t"
"inner:\n\t"
"    add %[p_tmp2], %[p_x], t5\n\t"
"    lh x13, 0(%[p_tmp2])\n\t"
"    add t2, x13, t1\n\t"
"    beq t2, %[target], set_flag\n\t"
"    addi t5, t5, 2\n\t"
"    addi x14, x14, -1\n\t"
"    bnez x14, inner\n\t"
"addi t4, t4, 2\n\t"
"addi t6, t6, -1\n\t"
"bnez t6, outer\n\t"
"j break\n\t"
"set_flag:\n\t"
"addi %[flag], %[flag], 1\n\t"
"break:\n\t"
